#index:
#    path: /
#    controller: App\Controller\DefaultController::index

weather_in_city:
  path: /weather/{city}
  controller: App\Controller\WeatherController:cityAction
  requirements:
    city: \d+

#location_index:
#  path:       /location
#  controller: App\Controller\LocationController:index

#measurement_index:
#  path:       /measurement
#  controller: App\Controller\MeasurementController:index



